### ISSUE TITLE
Pretty stack traces

### ISSUE THREAD

**Issue by Ben-Speakman** [clowdy/laravel-raven#2]
It seems that in the raw JSON data sent to Sentry the exception detail comes under the `sentry.interfaces.Message` interface and not `sentry.interfaces.Exception`. This means there is no pretty stack trace etc. Is this something wrong in my configuration?

**Comment by pulkitjalan** [comment]
Which version of this package are you using and are you able to send an example of the data sent?

**Comment by Ben-Speakman** [comment]
I am using 2.0.1. In sentry if I look at the raw JSON I can see:

````
sentry.interfaces.Message: {
    message: "[local] exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in /var/www/vhosts/xxx/app/Http/Controllers/HomeController.php:23 Stack trace: #0 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct() #1 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError() #2 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown() #3 /var/www/vhosts/xxx/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile() #4 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(0): Composer\Autoload\ClassLoader->loadClass() #5 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): spl_autoload_call() #6 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct() #7 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build() #8 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Container\Container->make() #9 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(83): Illuminate\Foundation\Application->make() #10 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->makeController() #11 /var/www/vhosts/xxx/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): ..."
},
````

Instead of:

````
sentry.interfaces.Exception: {
    exc_omitted: null,
    values: [
    {
        stacktrace: {
            frames: [
            {
                function: "null",
                abs_path: "/home/xxx/public_html/live/public/index.php",
                pre_context: [
                    "| the client's browser allowing them to enjoy the creative",
                    "| and wonderful application we have whipped up for them.",
                    "|",
                    "*/",
                ],
],

**Comment by pulkitjalan** [comment]
Looks like a bug with the package, ill have a fix out soon. Thanks.

**Comment by pulkitjalan** [comment]
I have pushed a fix for this bug however will need to require `"raven/raven": "dev-master"` until the guys at getsentry don't release the following commit: https://github.com/getsentry/raven-php/commit/a2c888f2671add58b4b7a7b3fe8ff156bf9506dd in a stable release.

**Comment by pulkitjalan** [comment]
There is also this following change to the installation section:

```
You also need to modify app\Exceptions\Hander.php to extend Clowdy\Raven\Handler instead of Illuminate\Foundation\Exceptions\Handler as below:

<?php namespace app\Exceptions;

use Exception;
// use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Clowdy\Raven\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
```

**Comment by Ben-Speakman** [comment]
Working for me now. Thanks!
